/* Auto-generated by tools/bump_version.py - do not edit manually */
#ifndef ESPNOWBUS_VERSION_H
#define ESPNOWBUS_VERSION_H

#define ESPNOWBUS_VERSION_MAJOR 1
#define ESPNOWBUS_VERSION_MINOR 0
#define ESPNOWBUS_VERSION_PATCH 1
#define ESPNOWBUS_VERSION_STR "1.0.1"

#endif // ESPNOWBUS_VERSION_H
