/* Auto-generated by tools/bump_version.py - do not edit manually */
#ifndef ESPNOWBUS_VERSION_H
#define ESPNOWBUS_VERSION_H

#define ESPNOWBUS_VERSION_MAJOR 1
#define ESPNOWBUS_VERSION_MINOR 2
#define ESPNOWBUS_VERSION_PATCH 0
#define ESPNOWBUS_VERSION_STR "1.2.0"

#endif // ESPNOWBUS_VERSION_H
