/* Auto-generated by tools/bump_version.py - do not edit manually */
#ifndef ESPNOWBUS_VERSION_H
#define ESPNOWBUS_VERSION_H

#define ESPNOWBUS_VERSION_MAJOR 0
#define ESPNOWBUS_VERSION_MINOR 0
#define ESPNOWBUS_VERSION_PATCH 2
#define ESPNOWBUS_VERSION_STR "0.0.2"

#endif // ESPNOWBUS_VERSION_H
